title: Dhruv Pendharkar
url: "https://dhruvpendharkar.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: null

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Projects"
   link: "/projects"
 - name: "Writing"
   link: "/writing"
